version: '3.3'
services:
  upload:
    restart: always
    volumes:
      - '/tmp/zfsv2/zenith_sata/18688947359/data/public/files/upload:/data/files'
      - './config/.ghs.yml:/app/config.yml'
    ports:
      - '8089:8000'
    environment:
      - FRP_DOWN=true
      - PUID=0
      - PGID=0
      - UMASK=022
    privileged: true
    user: root
    container_name: go-file-server
    image: 'uuxia.cn:8085/xxl6097/go-file-server:latest'

